name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'sbt'
    
    - name: Setup sbt
      uses: sbt/setup-sbt@v1
    
    - name: Build Assembly JAR
      run: sbt assembly
    
    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        files: target/scala-*/sparkinverse-*-assembly-*.jar
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TAG_TOKEN }}
